# Jaime Bohorquez
# NID: ja409704
# COP 4600 - Operating Systems, Spring 2021
# Programmed using Atom + iTerm2 on Mac OS Big Sur

# Makefile that manages compilation, execution, and cleaning of binaries
# belonging to shell.cpp

make:
	@echo Compiling...
	@g++ --std=c++11 -o shell shell.cpp
clean:
	@rm ./shell
run:
	@./shell
ping:
	@echo Pong!
