# Jaime Bohorquez
# NID: ja409704
# COP 4600 - Operating Systems, Spring 2021
# Programmed using Atom + iTerm2 on Mac OS Big Sur

# Makefile that manages compilation, execution, and cleaning of binaries
# belonging to mysh.cpp

make:
	@echo Compiling...
	@g++ -o mysh mysh.cpp
clean:
	@rm ./mysh
run:
	@./mysh
ping:
	@echo Pong!
all:
	make && make run
